version: '3'
services:
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        user: "1000"
        ports:
            - 3000:3000
        volumes:
            - $PWD/grafana_data:/var/lib/grafana:rw
        env_file:
            - .env
        restart: unless-stopped
        environment:
        - GF_SECURITY_ADMIN_USER=$GRAFANA_ADMIN_USERNAME
        - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
        - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
